// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjwvzdV8xO_aM67IxNuvVHSZaaWybrRtE',
    appId: '1:1054361605077:web:8697e82b567fbed34b235c',
    messagingSenderId: '1054361605077',
    projectId: 'itracelink-8c4ea',
    authDomain: 'itracelink-8c4ea.firebaseapp.com',
    storageBucket: 'itracelink-8c4ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjwvzdV8xO_aM67IxNuvVHSZaaWybrRtE',
    appId: '1:1054361605077:android:8697e82b567fbed34b235c',
    messagingSenderId: '1054361605077',
    projectId: 'itracelink-8c4ea',
    storageBucket: 'itracelink-8c4ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjwvzdV8xO_aM67IxNuvVHSZaaWybrRtE',
    appId: '1:1054361605077:ios:8697e82b567fbed34b235c',
    messagingSenderId: '1054361605077',
    projectId: 'itracelink-8c4ea',
    storageBucket: 'itracelink-8c4ea.firebasestorage.app',
    iosClientId: '1054361605077-placeholder.apps.googleusercontent.com',
    iosBundleId: 'rw.itracelink.app',
  );
}
